---
title: Adi's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: adichiru@gmail.com
description: Adi's views and thoughts on Cloud Computing, DevOps and other cool stuff
baseurl: ''
url: http://example.com
github_username: adichiru
permalink: "/:year/:month/:day/:title/"
disqus_shortname: adichiru
disqus_url: http://adichiru.github.io
markdown: kramdown
theme: minima
host: 0.0.0.0
port: 4000
